# docker-compose-jenkins.yml
version: '2.27.0'
services:
  jenkins_server:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    port:
      - 8080:8080
      - 50000:50000
    container_name: jenkins_server
    volumes:
      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins_agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: jenkinks_agent
    expose:
      - 22
    